title: Lawrence Lee
logo: profile%20pic-01.png
description: I am a dedicated professional with expertise in business analytics, project management, and real estate sales and marketing. Through my GitHub portfolio, I showcase my skills in data analysis, visualization, and strategic decision-making using tools such as SQL, Python, PowerBI, and Tableau.

Explore my projects to see how I leverage data to drive insights and make informed decisions. From analyzing market trends and creating effective marketing strategies to fostering client relationships and providing mentorship, my portfolio reflects my commitment to excellence and innovation in every project I undertake.
#description: text below image
theme: jekyll-theme-Minimal
