title: Lawrence Lee
logo: Casual_2024.png
description:
another_url: https://www.linkedin.com/in/lawrence-mklee/
github:
  zip_url: http://example.com/download.zip
  another_url: another value
theme: jekyll-theme-Minimal
